//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua conta está banida.
        ///Launcher foi finalizado..
        /// </summary>
        internal static string AUTH_ACC_BANNED {
            get {
                return ResourceManager.GetString("AUTH_ACC_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login disponível somente para membros da equipe..
        /// </summary>
        internal static string AUTH_ACC_NO_STAFF {
            get {
                return ResourceManager.GetString("AUTH_ACC_NO_STAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta inexistente!
        ///Verifique suas informações..
        /// </summary>
        internal static string AUTH_ACC_NOT_FOUND {
            get {
                return ResourceManager.GetString("AUTH_ACC_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fazendo login, por favor aguarde....
        /// </summary>
        internal static string AUTH_LOGIN {
            get {
                return ResourceManager.GetString("AUTH_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha incorreta.
        ///Verifique suas informações..
        /// </summary>
        internal static string AUTH_PASS_ERROR {
            get {
                return ResourceManager.GetString("AUTH_PASS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, faça o login..
        /// </summary>
        internal static string AUTH_TITLE {
            get {
                return ResourceManager.GetString("AUTH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_forms {
            get {
                object obj = ResourceManager.GetObject("bg_forms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_header {
            get {
                object obj = ResourceManager.GetObject("bg_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_close {
            get {
                object obj = ResourceManager.GetObject("btn_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_close_hover {
            get {
                object obj = ResourceManager.GetObject("btn_close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_min {
            get {
                object obj = ResourceManager.GetObject("btn_min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_min_hover {
            get {
                object obj = ResourceManager.GetObject("btn_min_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando arquivos importantes....
        /// </summary>
        internal static string CHECK_IMPORTANT_FILES {
            get {
                return ResourceManager.GetString("CHECK_IMPORTANT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando status do servidor....
        /// </summary>
        internal static string CHECK_SERVER_STATUS {
            get {
                return ResourceManager.GetString("CHECK_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectando ao servidor....
        /// </summary>
        internal static string CONNECTING_TO_SERVER {
            get {
                return ResourceManager.GetString("CONNECTING_TO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apagando arquivos inúteis....
        /// </summary>
        internal static string DELET_TRASH {
            get {
                return ResourceManager.GetString("DELET_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente sair?.
        /// </summary>
        internal static string EXIT_ASK {
            get {
                return ResourceManager.GetString("EXIT_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tudo pronto, já pode jogar!.
        /// </summary>
        internal static string GAME_IS_OK {
            get {
                return ResourceManager.GetString("GAME_IS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar PointBlank.exe.
        /// </summary>
        internal static string GAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma janela do jogo aberta..
        /// </summary>
        internal static string GAME_RUNNING {
            get {
                return ResourceManager.GetString("GAME_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma janela do Launcher aberta..
        /// </summary>
        internal static string LAUNCHER_RUNNING {
            get {
                return ResourceManager.GetString("LAUNCHER_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://projectelite.net/cadastrar/.
        /// </summary>
        internal static string LINK_REGISTER {
            get {
                return ResourceManager.GetString("LINK_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe seu LOGIN e SENHA!.
        /// </summary>
        internal static string LOGIN_PASS_REC {
            get {
                return ResourceManager.GetString("LOGIN_PASS_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe seu LOGIN!.
        /// </summary>
        internal static string LOGIN_REC {
            get {
                return ResourceManager.GetString("LOGIN_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NickName não definido..
        /// </summary>
        internal static string NO_NICKNAME {
            get {
                return ResourceManager.GetString("NO_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a alert.png.
        /// </summary>
        internal static string OBJECT_1 {
            get {
                return ResourceManager.GetString("OBJECT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a icon.ico.
        /// </summary>
        internal static string OBJECT_2 {
            get {
                return ResourceManager.GetString("OBJECT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, informe sua SENHA!.
        /// </summary>
        internal static string PASS_REC {
            get {
                return ResourceManager.GetString("PASS_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project Elite Evo- Launcher - NOT PUBLIC VERSION.
        /// </summary>
        internal static string PROJECT_NAME {
            get {
                return ResourceManager.GetString("PROJECT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conexão com o servidor foi finalizada..
        /// </summary>
        internal static string SERVER_CONNECTION_END {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conexão com o servidor interrompida.
        ///Launcher será finalizado..
        /// </summary>
        internal static string SERVER_CONNECTION_INTERRUPTED {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION_INTERRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel conectar-se ao servidor.
        ///Launcher será finalizado..
        /// </summary>
        internal static string SERVER_CONNECTION_UNKNOWN {
            get {
                return ResourceManager.GetString("SERVER_CONNECTION_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este launcher foi desativado, baixe a nova versão!.
        /// </summary>
        internal static string SERVER_IS_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("SERVER_IS_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O jogo está em manutenção no momento.
        ///Tenta novamente mais tarde!.
        /// </summary>
        internal static string SERVER_MAINTENANCE {
            get {
                return ResourceManager.GetString("SERVER_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Algo errado aconteceu...
        ///Entre em contato com o suporte!.
        /// </summary>
        internal static string SERVER_UNKNOWN_PACKAGE {
            get {
                return ResourceManager.GetString("SERVER_UNKNOWN_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro com seu token.
        ///Entre em contato com o suporte!.
        /// </summary>
        internal static string TOKEN_ERROR {
            get {
                return ResourceManager.GetString("TOKEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top_light {
            get {
                object obj = ResourceManager.GetObject("top_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
